### PR TITLE
Alter blameTest.java for PR #1565

### PR DESCRIPTION
**Pull request by FH-30**
Part of [PR #1565](https://github.com/reposense/RepoSense/pull/1565).

### CODE REVIEW

**Review by HCY123902 — APPROVED** [review]

**Comment by dcshzj** [comment]
I will be reverting this PR merge, as the original PR is not ready to be reviewed and it is breaking all other tests.

**Comment by FH-30** [comment]
@dcshzj I can see why its breaking the other tests. I actually meant to add this as a branch to this repo as opposed to actually merging it into the master branch. Is it possible to so do?

**Comment by dcshzj** [comment]
> @dcshzj I can see why its breaking the other tests. I actually meant to add this as a branch to this repo as opposed to actually merging it into the master branch. Is it possible to so do?

You can use the same approach as https://github.com/reposense/RepoSense/pull/1554#issuecomment-888405130, to add the test to your own branch so we can see if it works.

**Comment by dcshzj** [comment]
I have force pushed to master branch to revert this PR (and mainly to preserve the previous commit history, as our tests require that). @FH-30 Please do create a separate PR for this change, thank you!

**Comment by FH-30** [comment]
Alright that makes sense, my apologies for this mistake!

**Pull request merged**
