### PR TITLE
Update authorship tags to match test

### PR DESCRIPTION
**Pull request by sikai00**
This PR is with reference to [a pending PR in the RepoSense repo](https://github.com/reposense/RepoSense/pull/1857).

The names are updated to better reflect the changes made by that PR (which removes authorship regex validation checks). This should only be merged after the PR for RepoSense is merged.

### CODE REVIEW

**Review by chan-j-d — COMMENTED** [review]
Since the purpose of the PR is to make it easier for devs to understand what the test case is doing, I think it might be worthwhile to rename the individual lines to something like `unconventional author line 1`, `unconventional author line 2`, etc. 

I do remember being very confused as to what the lines meant the first time I looked at this test file and I think this change might be helpful. Iirc, the test cases only tests the number of lines attributed so this change shouldn't be too big of an issue

**Comment by sikai00** [comment]
> rename the individual lines to something like unconventional author line 1, unconventional author line 2, etc.

To clarify, do you mean only those lines not written by fake author?

image
something like this?

**Comment by chan-j-d** [comment]
@sikai00 yep! I believe the test case counts the number of lines attributed to those authors. do correct me if I'm wrong! This way I think it is somewhat more clear what the file together with the test case is trying to achieve

**Comment by sikai00** [comment]
> @sikai00 yep! I believe the test case counts the number of lines attributed to those authors. do correct me if I'm wrong! This way I think it is somewhat more clear what the file together with the test case is trying to achieve

Yes, the test case checks that the lines match the expected authors, the only thing that needs to updated is the JSON files in the main repo as they contain line content

**Comment by sikai00** [comment]
Unfortunately I deleted the fork remotely on Github when this PR was closed before, so I cannot make new commits to this PR anymore. Reopening a new PR!

**Pull request closed without merging**
