### PR TITLE
Add merge commit for unit test

### PR DESCRIPTION
**Pull request by ckcherry23**
## PR Purpose
This PR is to create a merge commit in a new branch to test whether merge commits are included in the generated report. 

## Delete Branch 
Please delete the branch named `1877-CommitInfoAnalyzerTest-mergeCommits` if possible as I had named it based on an existing branch name instead of the naming convention. This branch is not required anymore.

### CODE REVIEW

**Review by HCY123902 — APPROVED** [review]

**Comment by HCY123902** [comment]
Sorry I merged with rebase just now. It seems that these commits are not added to the commit history. Do you mind opening a new pull request with a new commit to make it work?

Alternatively, there is an existing merge commit [188e6af](https://github.com/reposense/testrepo-Alpha/commit/188e6afc49cafe0cf4c2a88d55e97679fa0b798b) that you can use as well

**Comment by ckcherry23** [comment]
@HCY123902 I think neither the merge commit nor the first commit by James has been merged into the branch. Could this be because both of them are empty commits?

**Comment by ckcherry23** [comment]
> Alternatively, there is an existing merge commit [188e6af](https://github.com/reposense/testrepo-Alpha/commit/188e6afc49cafe0cf4c2a88d55e97679fa0b798b) that you can use as well

Sure, I will try to work with the existing merge commit and open a new PR if needed later.

**Comment by HCY123902** [comment]
> > Alternatively, there is an existing merge commit [188e6af](https://github.com/reposense/testrepo-Alpha/commit/188e6afc49cafe0cf4c2a88d55e97679fa0b798b) that you can use as well
> 
> Sure, I will try to work with the existing merge commit and open a new PR if needed later.

yeah sure. You can still use this branch `1882-CommitInfoAnalyzerTest-analyzeCommits_mergeCommits_succes` for `CommitInfoAnalyzerTest` either way

**Pull request merged**
